name: flutter_wallet_validator
description: A blockchain wallet address validator for multiple networks (CORE, EVM, Bitcoin, Solana, Cardano). Validates formats and checksums.
version: 0.1.3
homepage: https://github.com/bchainhub/flutter_wallet_validator
repository: https://github.com/bchainhub/flutter_wallet_validator
documentation: https://github.com/bchainhub/flutter_wallet_validator#readme
issue_tracker: https://github.com/bchainhub/flutter_wallet_validator/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.29.1"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  convert: ^3.1.1
  pointycastle: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Keywords related to the package
topics:
  - blockchain
  - wallet
  - address
  - validator
  - crypto

# Funding links
funding:
  - https://github.com/sponsors/bchainhub
  - https://blockindex.net/address/cb7147879011ea207df5b35a24ca6f0859dcfb145999

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
