name: flutter_wallet_validator
description: A blockchain wallet address validator for multiple networks (CORE, EVM, Bitcoin, Solana, Cardano). Validates formats and checksums.
version: 0.1.2
homepage: https://github.com/bchainhub/flutter_wallet_validator
repository: https://github.com/bchainhub/flutter_wallet_validator
documentation: https://github.com/bchainhub/flutter_wallet_validator#readme
issue_tracker: https://github.com/bchainhub/flutter_wallet_validator/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.29.1"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  convert: ^3.1.1
  pointycastle: ^3.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry.
  plugin:
    platforms:
      android:
        package: digital.blockchainhub.flutter_wallet_validator
        pluginClass: FlutterWalletValidatorPlugin
      ios:
        package: digital.blockchainhub.flutter_wallet_validator
        pluginClass: FlutterWalletValidatorPlugin
      linux:
        package: digital.blockchainhub.flutter_wallet_validator
        pluginClass: FlutterWalletValidatorPlugin
      macos:
        package: digital.blockchainhub.flutter_wallet_validator
        pluginClass: FlutterWalletValidatorPlugin
      windows:
        package: digital.blockchainhub.flutter_wallet_validator
        pluginClass: FlutterWalletValidatorPlugin
      web:
        package: digital.blockchainhub.flutter_wallet_validator
        pluginClass: FlutterWalletValidatorWeb
        fileName: flutter_wallet_validator_web.dart
      wasm:
        pluginClass: FlutterWalletValidatorWasm
        fileName: flutter_wallet_validator_wasm.dart

# Keywords related to the package
topics:
  - blockchain
  - wallet
  - address
  - validator
  - crypto

# Funding links
funding:
  - https://github.com/sponsors/bchainhub
  - https://blockindex.net/address/cb7147879011ea207df5b35a24ca6f0859dcfb145999

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
