name: Report Bug 🪲
description: Create a bug report for Flutter Wallet Validator
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please provide as many details as possible to help us resolve the issue quickly.

  - type: markdown
    attributes:
      value: |
        Environment Details:

  - type: input
    id: flutter_version
    attributes:
      label: Flutter Version
      description: Output of 'flutter --version' command
      placeholder: e.g., Flutter 3.19.0 • channel stable
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Name and version of your operating system
      placeholder: e.g., Windows 11, macOS 14.1, Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Target Platform
      description: Platform where the issue occurs
      placeholder: e.g., Android, iOS, Web, macOS, Windows, Linux, Wasm
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: Bug Description
      description: Describe what the bug is and how it manifests
      placeholder: A clear description of what the bug is
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps needed to reproduce this behavior
      placeholder: |
        1. Call validateWalletAddress with '...'
        2. Pass options with '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen
      placeholder: A clear description of what you expected to happen
    validations:
      required: true

  - type: input
    id: package_version
    attributes:
      label: Package Version
      description: Version of flutter_wallet_validator package you're using
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots about the bug
