blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://pub.dev/packages/flutter_wallet_validator
    about: Read the Flutter Wallet Validator package documentation on pub.dev
  - name: Example App
    url: https://github.com/bchainhub/flutter_wallet_validator/tree/main/example
    about: Check out the example Flutter application
