name: Feature Request 🔮
description: Suggest an idea for Flutter Wallet Validator
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please provide details about your request to help us understand and evaluate it properly.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem would this feature solve? Please describe your use case.
      placeholder: A clear description of the problem you're facing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution and how it would work in Flutter
      placeholder: A clear description of how you'd like this to work
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What alternative solutions or workarounds have you considered?
      placeholder: Any alternative approaches you've thought about

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Example
      description: Provide a Dart/Flutter code example of how this feature could be implemented
      placeholder: |
        ```dart
        // Example implementation
        class WalletValidator {
          NetworkInfo validateAddress(String address, {
            ValidationOptions options,
          }) {
            // Your feature implementation
          }
        }
        ```

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples that could help explain the feature
      placeholder: Screenshots, diagrams, or additional explanations

  - type: input
    id: platform
    attributes:
      label: Target Platforms
      description: Which platforms would this feature target?
      placeholder: e.g., All platforms, Android only, iOS + Web
