name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.1'
        channel: 'stable'
        cache: true

    - name: Install Dependencies
      run: flutter pub get

    - name: Verify Formatting
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze Project
      run: flutter analyze

    - name: Run Tests
      run: flutter test

    - name: Check Publish Warnings
      run: flutter pub publish --dry-run
